// <auto-generated />
namespace Renfield.Inventory.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class m01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m01));
        
        string IMigrationMetadata.Id
        {
            get { return "201306301728040_m01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
