//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransformyClone.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransformyClone.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3, Roberto Carlos, soccer, Brazil
        ///35, Michael Jordan, baseball, USA
        ///6, James Lebron, basketball, USA
        ///10, Shinji Kagawa, soccer, Japan
        ///
        ///CARLOS, jersey number 3
        ///
        ///CARLOS, jersey number 3
        ///JORDAN, jersey number 35
        ///LEBRON, jersey number 6
        ///KAGAWA, jersey number 10
        ///.
        /// </summary>
        internal static string Sample1 {
            get {
                return ResourceManager.GetString("Sample1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2015-12-07T09:15:17-05:00
        ///1998-11-05T08:15:21-05:00
        ///1999-01-03T04:33:30-05:00
        ///2000-11-05T09:16:00-05:00
        ///
        ///07/12/2015 at 09h15
        ///
        ///07/12/2015 at 09h15
        ///05/11/1998 at 08h15
        ///03/01/1999 at 04h33
        ///05/11/2000 at 09h16
        ///.
        /// </summary>
        internal static string Sample2 {
            get {
                return ResourceManager.GetString("Sample2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joel, 1949, piano
        ///Lennon, 1940, guitar
        ///Grohl, 1969, drums
        ///Burton, 1962, bass
        ///
        ///{name: &apos;Joel&apos;, instrument: &apos;piano&apos;}
        ///
        ///{name: &apos;Joel&apos;, instrument: &apos;piano&apos;}
        ///{name: &apos;Lennon&apos;, instrument: &apos;guitar&apos;}
        ///{name: &apos;Grohl&apos;, instrument: &apos;drums&apos;}
        ///{name: &apos;Burton&apos;, instrument: &apos;bass&apos;}
        ///.
        /// </summary>
        internal static string Sample3 {
            get {
                return ResourceManager.GetString("Sample3", resourceCulture);
            }
        }
    }
}
