//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renfield.TextGeneration.Spike.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renfield.TextGeneration.Spike.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sherlock Holmes took his bottle from the corner of the mantel-piece and
        ///his hypodermic syringe from its neat morocco case. With his long,
        ///white, nervous fingers he adjusted the delicate needle, and rolled back
        ///his left shirt-cuff.  For some little time his eyes rested thoughtfully
        ///upon the sinewy forearm and wrist all dotted and scarred with
        ///innumerable puncture-marks. Finally he thrust the sharp point home,
        ///pressed down the tiny piston, and sank back into the velvet-lined
        ///arm-chair with a long sigh  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string english {
            get {
                return ResourceManager.GetString("english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAPITOLUL I
        ///
        ///
        ///Uraganul din 1865. Strigăte în văzduh. Un balon
        ///luat de o trombă. învelitoarea sfîşiată Cît cuprinzi
        ///cu ochii, numai mare. Cinci călători. Ce se petrece
        ///în nacela balonului. Un ţărm în zare. Deznodă-
        ///mîntul dramei.
        ///—	Urcăm ?
        ///—	Nu ! Dimpotrivă ! Coborîm.
        ///—	Mai rău, domnule Cyrus, ne prăvălim !
        ///—	Pentru dumnezeu I Atunci ce aşteptaţi ? Arun-
        ///caţi din lest1 1
        ///—	Uite. Am golit şi ultimul sac I
        ///— Balonul se ridică ?
        ///—	Nu !
        ///—	Parcă aud un clipocit de valuri 1
        ///—	Sîntem deasupra mării [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string romanian {
            get {
                return ResourceManager.GetString("romanian", resourceCulture);
            }
        }
    }
}
