//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renfield.VideoSpinner.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renfield.VideoSpinner.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {04921709-B159-11D1-9207-0000F8758E66}, HeightField
        ///{16B280C5-EE70-11D1-9066-00C04FD9189D}, Fade
        ///{16B280C8-EE70-11D1-9066-00C04FD9189D}, BasicImage
        ///{2BC0EF29-E6BA-11D1-81DD-0000F87557DB}, Convolution
        ///{353359C1-39E1-491B-9951-464FD8AB071C}, Movie Maker Special Effect Inplace 1 Input
        ///{3D2807C2-43DE-11D2-9900-0000F803FF7A}, Spin
        ///{421516C1-3CF8-11D2-952A-00C04FA34F05}, Chroma
        ///{42B07B28-2280-4937-B035-0293FB812781}, Redirect
        ///{4ABF5A06-5568-4834-BEE3-327A6D95A685}, Matrix
        ///{4CCEA634-FBE0-11D1-906A-00C04FD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Transitions {
            get {
                return ResourceManager.GetString("Transitions", resourceCulture);
            }
        }
    }
}
