//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Renfield.Anagrams.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Renfield.Anagrams.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm from http://stackoverflow.com/a/1924561/31793
        ///Word list from http://www.puzzlers.org/pub/wordlists/unixdict.txt
        ///.
        /// </summary>
        internal static string ExternalResources {
            get {
                return ResourceManager.GetString("ExternalResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10th
        ///1st
        ///2nd
        ///3rd
        ///4th
        ///5th
        ///6th
        ///7th
        ///8th
        ///9th
        ///a
        ///a&amp;m
        ///a&amp;p
        ///a&apos;s
        ///aaa
        ///aaas
        ///aarhus
        ///aaron
        ///aau
        ///aba
        ///ababa
        ///aback
        ///abacus
        ///abalone
        ///abandon
        ///abase
        ///abash
        ///abate
        ///abater
        ///abbas
        ///abbe
        ///abbey
        ///abbot
        ///abbott
        ///abbreviate
        ///abc
        ///abdicate
        ///abdomen
        ///abdominal
        ///abduct
        ///abe
        ///abed
        ///abel
        ///abelian
        ///abelson
        ///aberdeen
        ///abernathy
        ///aberrant
        ///aberrate
        ///abet
        ///abetted
        ///abetting
        ///abeyance
        ///abeyant
        ///abhorred
        ///abhorrent
        ///abide
        ///abidjan
        ///abigail
        ///abject
        ///ablate
        ///ablaze
        ///able
        ///ablution
        ///abner
        ///abnormal
        ///abo
        ///aboard
        ///abode
        ///aboli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WordsList {
            get {
                return ResourceManager.GetString("WordsList", resourceCulture);
            }
        }
    }
}
