// <auto-generated />
namespace Renfield.Inventory.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class m04 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m04));
        
        string IMigrationMetadata.Id
        {
            get { return "201307040636501_m04"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
